### ISSUE TITLE
Symlink style credentials

### ISSUE THREAD

**Issue by rkoster** [cloudfoundry-incubator/credhub#21]
As a credhub user, I would like to be able to have the same credential be available in different paths.
To be able use bosh generated variables (`/{director_name}/{deployment_name}/{variable_name}`) in concourse (`/concourse/{team_name}/{variable_name}`).

Related issues:
- https://github.com/concourse/concourse/issues/291#issuecomment-309067106
- https://github.com/hashicorp/vault/issues/1284

**Comment by crawsible** [comment]
@rkoster Is there something you're unable to do without this feature, or is this more of a quality of life improvement?

**Comment by danjahner** [comment]
I've received similar feature requests from users in the past. I think this is coming up specifically in context of Concourse because it forces a namespace, whereas BOSH allows you to work around the problem by escape the conventional namespace scheme with a leading slash.

The primary use case, as I understand it, is where you have a Concourse job that requires a credential which is established via a BOSH deployment. For example, I deploy a database with BOSH, then run a Concourse job that uses the database credentials to perform an action. 

This can be accomplished by duplicating the BOSH credential to the required Concourse namespace, but then you run into manual value sync trouble when you rotate. 

Allowing a symlink-like feature would remove the need for duplication and provide a controlled way to cross namespaces without exposing too much access.

Let me know if I've mischaracterized that, @rkoster.

**Comment by rkoster** [comment]
@danjahner is right, this is exactly the use-case we run into as well.

**Comment by crawsible** [comment]
@danjahner, thank you for the additional context.

@rkoster My preference would be for Concourse to mimic BOSH's behavior of skipping the namespace when an absolute path is provided, as @xoebus mentioned in the concourse issue thread https://github.com/concourse/concourse/issues/291#issuecomment-309075869. As our access control model becomes more robust and path prefixes begin to accept their own ACEs, symlinks could get hairy.

@jama-pivotal @vito any appetite for mimicking the BOSH director's handing of relative and absolute paths in manifests?

**Comment by ramonskie** [comment]
any news on this?
a copy option in the credhub cli can also be an option

**Comment by crawsible** [comment]
@ramonskie This feels like a workaround to sidestep a limitation imposed by Concourse, rather than a problem that CredHub needs to solve, especially since this exact same behavior (I need to refer to X value that lives outside my CredHub consumer's implied namespace) is supported by BOSH. My suggestion is requesting that Concourse support absolute path references to values in CredHub. If they have a reason why they don't want to support that, I'd want to make sure adding symlinks doesn't just recreate some problem they're trying to avoid in a different way.
