### ISSUE TITLE
Do we have any web UI for credhub?

### ISSUE THREAD

**Issue by goprasad** [cloudfoundry-incubator/credhub#52]
Do we have any web UI for credhub?

If not, do we have any plans in near future?

**Comment by martys34** [comment]
@goprasad @jparnala @crawsible 
We do not have a web UI and I do not believe there are any plans for one in the near future.

**Comment by shreddedbacon** [comment]
I have been looking for a web ui for credhub too.

It would be handy to be able to log in to a web UI to retrieve or update credentials rather than having to access terminal.
I've found myself on a few occasions needing to log in to `system A` that has its admin password in credhub, but I can manage `system A` from my mobile. Having to go into the CLI to retrieve the credential is tedious when you only have a mobile phone on you.

It would also be good to be able to update certificates and such via a web ui, it means that windows users in a team are able to update credentials without having to install any additional tools.

**Comment by shreddedbacon** [comment]
I wrote a quick webui for credhub here https://github.com/shreddedbacon/credhub-webui
Has not been thoroughly tested, so use it at your own risk.

**Comment by goprasad** [comment]
Thank you @shreddedbacon  and will try this.

**Comment by shreddedbacon** [comment]
There is a bish release for it now too. https://github.com/shreddedbacon/credhub-webui-boshrelease

**Comment by ankeesler** [comment]
Thank you @shreddedbacon for your contribution! Closing this issue.
