### ISSUE TITLE
More obvious logging expected

### ISSUE THREAD

**Issue by Ykisialiou** [cloudfoundry-incubator/credhub#59]
I understand that it's cosmetic change, but probably worth mentioning, to make product better.

What version of the credhub server you are using?
`Server Version: 2.5.4`

What version of the credhub cli you are using?
`CLI Version: 2.5.3`

If you were attempting to accomplish a task, what was it you were attempting to do?
Set CA certificate with empty `Certificate` and `Private Key` fields with the command like this
`credhub set -n  /my_credential_name  -t rsa  -r /ca.crt`

What did you expect to happen?
The log output with smth similar to `certificate and private key are mandatory for rsa type`

What was the actual behavior?
`At least one key value must be set. Please validate your input and retry your request.`
The log output is a bit confusing and can lead to wrong debug direction

Please confirm where necessary:
* [X] I have included a log output
* [X] My log includes an error message
* [X] I have included steps for reproduction

If you are a PCF customer with an Operation Manager (PCF Ops Manager) please direct your questions to support (https://support.pivotal.io/)

**Comment by martys34** [comment]
@Ykisialiou The command you ran: `credhub set -n /my_credential_name -t rsa -r /ca.crt` does not actually pass a private key. The flag `-r` is not a valid flag for the rsa type (it is the flag for a root CA on a certificate type). I think the flag you meant to pass was `-p` which would have worked because you can leave the public key out in an rsa type.

Therefore, the error message that `at least one key value must be set` seems to make sense because you did not provide any of the rsa key values.

**Comment by Ykisialiou** [comment]
Sure, thanks for answer. Agree with you, I believe it can be closed then.
