### ISSUE TITLE
Delete method in CredentialDataService not transactional. Possible StaleStateException 

### ISSUE THREAD

**Issue by mqkuhnen** [cloudfoundry-incubator/credhub#65]
Hello CredHub team, I had look at the delete implementation of the CredentialDataService.java 
What drew my attention here is the fact that there is a find, and a delete method that do not happen inside a transaction. I would expect to have the delete method transactional and not only the deleteByNameIgnoreCase as transactional.
Could not this cause problems during the deletion of the credentials? The find method could retrieve a cached version of the credential that is not actual anymore. And then the deleteByNameIgnoreCase method would fail, since it might happen that this credential is not there anymore.  This seems a strange behaviour that could lead to a StaleStateException https://docs.jboss.org/hibernate/orm/3.5/api/org/hibernate/StaleStateException.html

**Comment by tomkennedy513** [comment]
Hi @mqkuhnen, This does seem odd that we are being inconsistent. We will schedule this to be updated! Thank you!

**Comment by tomkennedy513** [comment]
The reason that delete method is not transactional is because that find is solely used for the audit logs and doesn't affect the delete. The audit log only cares about the credential name and credential uuid which cannot be changed, so there is no case in which the data written to the audit log would differ from the credential that is actually deleted.
